import { AIPersonality, AIPersonalityId, PresetVariant } from '../types/chess';

export const AI_PERSONALITIES: Record<AIPersonalityId, AIPersonality> = {
  lion_mode: {
    id: 'lion_mode',
    name: '🦁 LION MODE — Impossible to Beat',
    subtitle: 'Supreme Engine Apex',
    icon: '🦁',
    color: 'amber-300',
    borderColor: 'border-amber-400/80',
    badgeBg: 'bg-gradient-to-r from-amber-500/25 to-yellow-600/25',
    glowColor: 'shadow-[0_0_25px_rgba(212,175,55,0.4)]',
    skillLevel: 20,
    depth: 28,
    moveTime: 5000,
    contempt: 200,
    multiPv: 1,
    hash: 128,
    description: 'Supreme Strength — Depth 28–30+, NNUE evaluation, 15+ move GM book, double anti-blunder verification.',
    playstyle: 'Flawless calculation, 15+ move grandmaster book, tablebase endgame conversion, and double-verified anti-blunder guard.',
    psychologicalTag: 'Apex Predator'
  },
  god_mode: {
    id: 'god_mode',
    name: '👑 GOD MODE (Unbeatable)',
    subtitle: 'Grandmaster Singularity',
    icon: '👑',
    color: 'yellow-400',
    borderColor: 'border-yellow-500/60',
    badgeBg: 'bg-yellow-500/20',
    glowColor: 'shadow-[0_0_20px_rgba(234,179,8,0.3)]',
    skillLevel: 20,
    depth: 24,
    moveTime: 3500,
    contempt: 100,
    multiPv: 1,
    hash: 128,
    description: 'Grandmaster precision — Skill 20, Depth 24+, Opening Book, Zero Blunders.',
    playstyle: 'Flawless calculation, opening book, tablebase endgame precision, and blunder-proof verification.',
    psychologicalTag: 'Grandmaster'
  },
  tournament_player: {
    id: 'tournament_player',
    name: '🏆 Tournament Player',
    subtitle: 'FIDE Master',
    icon: '🏆',
    color: 'amber-400',
    borderColor: 'border-amber-500/40',
    badgeBg: 'bg-amber-500/15',
    skillLevel: 20,
    depth: 18,
    moveTime: 1500,
    contempt: 50,
    multiPv: 2,
    hash: 64,
    description: 'Skill Level 20, Depth 18. Razor-sharp tactical precision with zero margin for error.',
    playstyle: 'Flawless calculation and disciplined tactical punishment',
    psychologicalTag: 'FIDE Master'
  },
  human_pro: {
    id: 'human_pro',
    name: '🔵 Human Pro',
    subtitle: 'Club Expert',
    icon: '🔵',
    color: 'blue-400',
    borderColor: 'border-blue-500/40',
    badgeBg: 'bg-blue-500/15',
    skillLevel: 12,
    depth: 11,
    moveTime: 850,
    contempt: 20,
    multiPv: 2,
    hash: 32,
    description: 'Skill Level 12, Depth 11. Solid club tournament accuracy and positional strength.',
    playstyle: 'Solid positional play and disciplined fundamentals',
    psychologicalTag: 'Club Expert'
  },
  human_play: {
    id: 'human_play',
    name: '🟢 Human Play',
    subtitle: 'Smart Beginner',
    icon: '🟢',
    color: 'emerald-400',
    borderColor: 'border-emerald-500/40',
    badgeBg: 'bg-emerald-500/15',
    skillLevel: 3,
    depth: 4,
    moveTime: 500,
    contempt: 0,
    multiPv: 2,
    hash: 16,
    description: 'Skill Level 3, Depth 4. Natural human development with realistic minor oversights.',
    playstyle: 'Natural casual moves with realistic human tempo',
    psychologicalTag: 'Smart Beginner'
  },
  extreme_fast: {
    id: 'extreme_fast',
    name: '⚡ Extreme Fast (Rush)',
    subtitle: 'Speed Aggressor',
    icon: '⚡',
    color: 'cyan-400',
    borderColor: 'border-cyan-500/40',
    badgeBg: 'bg-cyan-500/15',
    skillLevel: 20,
    depth: 14,
    moveTime: 500,
    contempt: 200,
    multiPv: 2,
    hash: 32,
    description: 'Skill Level 20, Depth 14, Contempt 200, MoveTime 500ms. Hyper-aggressive blitz attacks.',
    playstyle: 'Relentless king attacks, rapid sacrifices, and mate chases',
    psychologicalTag: 'Speed Aggressor'
  },
  extreme_slow: {
    id: 'extreme_slow',
    name: '🐢 Extreme Slow (Mastermind)',
    subtitle: 'Deep Calculator',
    icon: '🐢',
    color: 'purple-400',
    borderColor: 'border-purple-500/40',
    badgeBg: 'bg-purple-500/15',
    skillLevel: 20,
    depth: 28,
    moveTime: 3500,
    contempt: 50,
    multiPv: 2,
    hash: 64,
    description: 'Skill Level 20, Depth 28, MoveTime 3500ms. Deep exhaustive positional analysis.',
    playstyle: 'Deep exhaustive calculation with immaculate endgame technique',
    psychologicalTag: 'Mastermind'
  },
  hacker_extreme: {
    id: 'hacker_extreme',
    name: '🕶️ Hacker Extreme',
    subtitle: 'Swag Mastermind',
    icon: '🕶️',
    color: 'rose-400',
    borderColor: 'border-rose-500/40',
    badgeBg: 'bg-rose-500/15',
    skillLevel: 20,
    depth: 16,
    moveTime: 1000,
    contempt: 80,
    multiPv: 3,
    hash: 64,
    description: 'Skill Level 20, MultiPV 3. Bypasses standard lines to play unorthodox, psychological master moves.',
    playstyle: 'Unorthodox, psychologically jarring yet tactically sound moves',
    psychologicalTag: 'Chaos Mastermind'
  }
};

export const PRESET_VARIANTS: PresetVariant[] = [
  {
    id: 'standard',
    name: 'Standard Game',
    category: 'standard',
    description: 'Official FIDE standard starting position',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    icon: '♟️',
    whiteTurn: true
  },
  {
    id: 'endgame_queen',
    name: 'Queen & Pawn Endgame',
    category: 'endgame',
    description: 'Precision queen and king technical endgame',
    fen: '8/6k1/8/8/4P3/8/5Q2/6K1 w - - 0 1',
    icon: '♛',
    whiteTurn: true
  },
  {
    id: 'tactical_puzzle',
    name: 'Greek Gift Sacrifice',
    category: 'puzzle',
    description: 'Classic Bxh7+ kingside attacking puzzle',
    fen: 'r1bq1rk1/ppp2ppp/2n1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQ - 4 7',
    icon: '🎯',
    whiteTurn: true
  }
];
